learning_template/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# template tagging
app_name = 'basic_app'

urlpatterns= [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^others/$',views.others,name='others'),
]

learning_template/learning_template/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),

]

learning_template/basic_app/models.py
from django.db import models

# Create your models here.

learning_template/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'Hello World', 'number':100}
    return render(request,'basic_app/index.html',context_dict)

def others(request):
    return render(request,'basic_app/others.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_template/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:others' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
          <!-- outside will be inherited -->
        {% endblock %}
      </div>

    </div>
  </body>
</html>

learning_template/templates/basic_app/index.html
<!DOCTYPE html>
  {% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to Index</h1>
    <h1>This is index.html Page</h1>
    <h1>{{ text|cut:"World" }}</h1>
    <h1>{{ number|add:"99" }}</h1>
    {% endblock %}

learning_template/templates/basic_app/others.html
<!DOCTYPE html>
  {% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to Others</h1>
    <h2>Example of inheritance</h2>
    {% endblock %}

learning_template/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative URL Templates</h1>
    <a href="{% url 'basic_app:others' %}">The other page</a><br>
    <a href="{% url 'admin:index' %}">Admin Page</a><br>
    <a href="{% url 'index' %}">Index Page</a>
  </body>
</html>